import { Platform } from 'react-native';

const styleConfigs = {
  // new

  //color
  BORDER_COLOR: '#F4F4F6',
  COLOR_WHITE: '#FFF',
  COLOR_RED: 'red',

  //Property
  BORDER_WIDTH: 1,
  VERTICLE: 10,
  VERTICLE_20: 20,
  VIEW_ROW: 'row',
  VIEW_ABSOLUTE: 'absolute',

  CENTER: 'center',

  // old
  PURPLE_COLOR: '#55529E',
  PURPLE_PALE_COLOR: '#5F5EA3',
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '500',
  FONT_WEIGHT_BOLD: '700',
  BACKGROUND_COLOR_LIGHT: '#FAFAFA',
  CONTAINER_PADDING: 20,
  TEXT_INPUT_PADDING: 10,
  HEIGHT_BUTTON: 40,
  BORDER_RADIUS_BUTTON: 20,
  BACKGROUND_COLOR_CONTAINER: '#FAFAFA'
};

export default styleConfigs;
